### getProduct Get 
GET  http://localhost:8080/api/v2/product HTTP/1.1
### getProduct Get with token
GET  http://localhost:8080/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDY0MTE3MTAsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.lCImo7zdqD8-IP0XAg6D7IA_eJp03eb_vNGFQ-oQVw8
### createProduct Post
POST http://localhost:8080/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDY3NTQ0ODgsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.hyMGreiBJiecjahXyiSegZDs6EOel1KaA_p6W55dqv0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Angular 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

300
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Edit 
PUT http://localhost:8080/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTk4OTg1OTQsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.e8ZcnQFnye_DldUnzyqfth37SVB0hp8ZEjvRCy7th4s
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id";

4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Arduino board (Edit)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

101
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

200
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test_2nd.jpg"
Content-Type: image/png

< ./test2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--