### getProduct Get 
GET  http://localhost:8080/api/v2/product HTTP/1.1
### getProduct Get with token
GET  http://localhost:8080/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDY0MTE3MTAsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.lCImo7zdqD8-IP0XAg6D7IA_eJp03eb_vNGFQ-oQVw8
### createProduct Post
POST http://localhost:8080/api/v2/product HTTP/1.1
Content-Type: application/json